#!/bin/bash

# Alacritty Cross-Platform Configuration Setup
# Generates the appropriate alacritty.toml based on the platform

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
CONFIG_DIR="$HOME/.config/alacritty"

# Detect platform
detect_platform() {
    case "$(uname -s)" in
        Darwin*)
            echo "Darwin"
            ;;
        Linux*)
            echo "linux"
            ;;
        CYGWIN*|MINGW*|MSYS*)
            echo "windows"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

# Allow override via environment variable
PLATFORM="${PLATFORM:-$(detect_platform)}"
echo "Setting up Alacritty configuration for platform: $PLATFORM"

# Ensure config directory exists
mkdir -p "$CONFIG_DIR"

# Generate final alacritty.toml based on platform
case "$PLATFORM" in
    Darwin|macos)
        cat > "$CONFIG_DIR/alacritty.toml" << 'EOF'
# Alacritty Terminal Configuration
# Generated for platform: macOS
# DO NOT EDIT MANUALLY - Generated by setup-alacritty-config.sh

# Import base theme
[general]
import = ["~/.config/alacritty/themes/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6
opacity = 0.9
blur = true
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 40

[font]
normal.family = "JetBrains Mono"
size = 15
offset.y = 1

# macOS-specific key bindings
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"
EOF
        ;;
    linux)
        cat > "$CONFIG_DIR/alacritty.toml" << 'EOF'
# Alacritty Terminal Configuration
# Generated for platform: Linux
# DO NOT EDIT MANUALLY - Generated by setup-alacritty-config.sh

# Import base theme
[general]
import = ["~/.config/alacritty/themes/themes/dracula.toml"]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"

[window]
padding.x = 6
padding.y = 6
opacity = 0.9
blur = true

[window.dimensions]
columns = 120
lines = 40

[font]
normal.family = "JetBrains Mono"
size = 14
offset.y = 0

# Linux-specific key bindings
[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"
EOF
        ;;
    *)
        echo "Error: Unsupported platform: $PLATFORM"
        exit 1
        ;;
esac

echo "Alacritty configuration generated successfully!"
echo "Config file: $CONFIG_DIR/alacritty.toml"